name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup rust toolchain, cache and cargo-codspeed binary
      uses: moonrepo/setup-rust@v1
      with:
        channel: stable
        cache-target: release
        bins: cargo-codspeed

    - name: Run tests
      run: cargo test --verbose
